version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    groups:
      crazy-max-dot-github:
        patterns:
          - "crazy-max/.github/*"
    labels:
      - "area/dependencies"
      - "bot"
