run:
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go$"

  modules-download-mode: vendor

  build-tags:

linters:
  enable:
    - gofmt
    - govet
    - deadcode
    - depguard
    - goimports
    - ineffassign
    - misspell
    - unused
    - varcheck
    - revive
    - staticcheck
    - typecheck
    - nolintlint
    - gosec
    - forbidigo
  disable-all: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # The io/ioutil package has been deprecated.
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil
  forbidigo:
    forbid:
      - '^fmt\.Errorf(# use errors\.Errorf instead)?$'
  gosec:
    excludes:
      - G204  # Audit use of command execution
      - G402  # TLS MinVersion too low
    config:
      G306: "0644"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
