package store

var adjectives = []string{
	"able", "alert", "basic", "bold", "brisk", "bright", "brisk", "calm",
	"clean", "clear", "clever", "close", "cool", "crisp", "curious", "damp",
	"dark", "deep", "dry", "eager", "early", "empty", "even", "fair",
	"fast", "fine", "firm", "flat", "fresh", "gentle", "good", "grand",
	"great", "green", "hard", "high", "honest", "hot", "just", "keen",
	"kind", "large", "late", "lazy", "light", "long", "low", "lucky",
	"main", "major", "mild", "minor", "modern", "narrow", "neat", "new",
	"nice", "odd", "open", "plain", "prime", "proud", "pure", "quick",
	"quiet", "rapid", "rare", "raw", "ready", "rich", "right", "rough",
	"round", "safe", "sharp", "short", "shy", "simple", "slim", "slow",
	"smart", "smooth", "soft", "solid", "sound", "square", "stable", "steep",
	"still", "straight", "strong", "sure", "sweet", "tall", "thick", "tidy",
	"tight", "tiny", "true", "vast", "warm", "weak", "wide", "wild",
	"wise", "young", "zesty", "blank", "brief", "chill", "dry", "faint",
}

var nouns = []string{
	"arch", "atom", "aura", "band", "bank", "beam", "bell", "berry",
	"blade", "block", "bloom", "bluff", "bolt", "breeze", "bridge", "brook",
	"brush", "burst", "cabin", "cable", "camp", "cell", "chalk", "chime",
	"cloud", "cliff", "core", "craft", "crest", "curve", "dawn", "disk",
	"dome", "drift", "drop", "dust", "edge", "ember", "field", "fire",
	"flake", "flash", "flock", "flow", "fog", "forge", "frame", "gap",
	"gem", "glade", "gleam", "glow", "grain", "grove", "gust", "halo",
	"harbor", "haze", "hill", "hollow", "ice", "isle", "knot", "lake",
	"leaf", "light", "line", "link", "loop", "map", "maze", "meadow",
	"mist", "moon", "moss", "mount", "nest", "node", "note", "ocean",
	"orb", "pack", "path", "peak", "pebble", "petal", "pine", "plane",
	"plate", "plume", "pond", "pool", "pulse", "quest", "raven", "reef",
	"ridge", "ring", "rise", "river", "rock", "root", "sail", "scale",
	"scope", "shade", "shard", "shell", "shine", "ship", "shock", "shore",
	"signal", "sky", "slate", "snow", "song", "spark", "spike", "spore",
	"spring", "stack", "star", "stem", "stone", "storm", "stream", "stripe",
	"sun", "surf", "swirl", "tail", "tide", "track", "trail", "tree",
	"trunk", "vale", "vault", "veil", "vibe", "void", "wake", "wave",
	"web", "wheel", "whirl", "wind", "wing", "wire", "wood", "yard",
	"zone", "badge", "bar", "base", "beacon", "bin", "blade", "blaze",
	"branch", "brick", "bud", "bulb", "button", "byte", "carve", "catch",
	"chain", "chip", "clamp", "clip", "coil", "cradle", "crash", "crest",
	"dash", "dial", "dock", "echo", "engine", "flick", "frame", "fuse",
	"gear", "grid", "groove", "guard", "hinge", "hook", "joint", "key",
	"knob", "lever", "lock", "loop", "lug", "mesh", "motor", "nail",
	"pad", "peg", "pin", "plate", "plug", "port", "press", "rack",
	"rail", "ramp", "rivet", "rod", "roll", "rope", "seal", "shaft",
	"sheet", "shelf", "skid", "slot", "snap", "socket", "spark", "spool",
	"spur", "stack", "stalk", "strap", "stud", "tab", "tag", "tape",
	"tile", "track", "tray", "tube", "valve", "vent", "vessel", "wedge",
}
