#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

: ${TARGETPLATFORM=$CLI_PLATFORM}

platformFlag=""
if [ -n "$TARGETPLATFORM" ]; then
  platformFlag="--platform $TARGETPLATFORM"
fi

buildxCmd build $platformFlag \
  --target "binaries" \
  --output "type=local,dest=./bin/" \
  .
