#!/usr/bin/env bash

OUT=${1:-release-out}

. $(dirname $0)/util
set -eu -o pipefail

: ${PLATFORMS=linux/amd64}

importCacheFlags=""
if [[ -n "$cacheRefFrom" ]] && [[ "$cacheType" = "local" ]]; then
  for ref in $cacheRefFrom; do
    importCacheFlags="$importCacheFlags--cache-from=type=local,src=$ref "
  done
fi

buildxCmd build $importCacheFlags \
  --target "release" \
  --platform "$PLATFORMS" \
  --output "type=local,dest=$OUT" \
  $currentcontext

# wrap binaries
{ set +x; } 2>/dev/null
if [[ $PLATFORMS =~ "," ]]; then
  mv -f ./$OUT/**/* ./$OUT/
  find ./$OUT -type d -empty -delete
fi