#!/usr/bin/env bash

set -eu -o pipefail

: ${BUILDX_CMD=docker buildx}

output=$(mktemp -d -t buildx-output.XXXXXXXXXX)
(set -x ; ${BUILDX_CMD} bake --set "*.output=$output" update-docs)
rm -rf ./docs/reference/*
cp -R "$output"/out/* ./docs/
rm -rf $output
