#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

output=$(mktemp -d -t buildx-output.XXXXXXXXXX)

buildxCmd build \
  --target "update" \
  --output "type=local,dest=$output" \
  --file "./hack/dockerfiles/docs.Dockerfile" \
  .

rm -rf ./docs/reference/*
cp -R "$output"/out/* ./docs/
rm -rf $output
