.nh
.TH "DOCKER-BUILDX-_INTERNAL_SERVE" "1" "Mar 2024" "" ""

.SH NAME
.PP
docker-buildx-_INTERNAL_SERVE -


.SH SYNOPSIS
.PP
\fBdocker buildx _INTERNAL_SERVE [OPTIONS]\fP


.SH DESCRIPTION

.SH OPTIONS
.PP
\fB--config\fP=""
	Specify buildx server config file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for _INTERNAL_SERVE


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--builder\fP=""
	Override the configured builder instance


.SH SEE ALSO
.PP
\fBdocker-buildx(1)\fP
