.nh
.TH "DOCKER-BUILDX-INSTALL" "1" "Mar 2024" "" ""

.SH NAME
.PP
docker-buildx-install - Install buildx as a 'docker builder' alias


.SH SYNOPSIS
.PP
\fBdocker buildx install\fP


.SH DESCRIPTION
.PP
Install buildx as a 'docker builder' alias


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH SEE ALSO
.PP
\fBdocker-buildx(1)\fP
