.nh
.TH "DOCKER-BUILDX-VERSION" "1" "Mar 2024" "" ""

.SH NAME
.PP
docker-buildx-version - Show buildx version information


.SH SYNOPSIS
.PP
\fBdocker buildx version\fP


.SH DESCRIPTION
.PP
View version information

.EX
$ docker buildx version
github.com/docker/buildx v0.11.2 9872040b6626fb7d87ef7296fd5b832e8cc2ad17

.EE


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH SEE ALSO
.PP
\fBdocker-buildx(1)\fP
