.nh
.TH "DOCKER-BUILDX-UNINSTALL" "1" "Mar 2024" "" ""

.SH NAME
.PP
docker-buildx-uninstall - Uninstall the 'docker builder' alias


.SH SYNOPSIS
.PP
\fBdocker buildx uninstall\fP


.SH DESCRIPTION
.PP
Uninstall the 'docker builder' alias


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall


.SH SEE ALSO
.PP
\fBdocker-buildx(1)\fP
