name: labeler

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] does not checkout, safe to use pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read # same as global permission
      pull-requests: write # required for writing labels
    steps:
      -
        name: Run
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          sync-labels: true
